server:
    port: 8081
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/spring-zen
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                format_sql: true
        show-sql: true
